### ISSUE TITLE
Annotating multi-organism processes

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-shapes#129]
In working on some models for defense responses in C. elegans, I'm not clear on how to model the action of the pathogen, e.g. a Gram-negative bacterium, in the pathway.

Should the pathogen be an input to some type of host receptor function or should an MF enabled by some gp of the pathogen have a causal relation to the receptor function? Or something else?

The current state of knowledge is incomplete for the pathway we're modeling, but this bears on what is considered a valid entry for 'has input' and how to represent an MF for a pathogen gp that may not have evolved for the function modeled in this process.

**Comment by pgaudet** [comment]
I would look at GO:0052027 'modulation by symbiont of host signal transduction pathway'
and children. 

Pascale

**Comment by vanaukenk** [comment]
We've addressed this issue by advising that curators use the 'has input' annotation extension to the relevant process and populate it with an NCBITaxon id.
