### ISSUE TITLE
python validator doesn't seem to test all files

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-shapes#133]
@cmungall I may just be misunderstanding how this works, but I am running into files that cause problems for shaclex but seem to pass python, e.g. `should_fail/fail_no_evidence_4.ttl`.

But when I run `make test` in python, I don't see any output about this file.

**Comment by vanaukenk** [comment]
@balhoff 

Can we close this ticket?

**Comment by balhoff** [comment]
I suppose so, I don't think this is being used for automated checks now.
