### ISSUE TITLE
Remove MacromolecularMachine shape?

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-shapes#135]
The schema contains an unused shape `MacromolecularMachine`. Currently it is restricting `@<Protein> OR @<Complex>`. Elsewhere we are frequently specifying `@<Complex> OR @<InformationBiomacromolecule>`. Should we:

- update `MacromolecularMachine` to restrict `@<Complex> OR @<InformationBiomacromolecule>` and make use of it.

or

- eliminate `MacromolecularMachine`

**Comment by pgaudet** [comment]
I think we can remove it. I don't think this is needed anymore.
