### ISSUE TITLE
Proposed updates to Molecular Function shape

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-shapes#137]
From 2019-08-07 call, here are the suggested updates to the Molecular Function shape.
@balhoff @cmungall @thomaspd @pgaudet  - please review

enabled_by:  ( @\<ProteinContainingComplex> OR @\<InformationBiomacromolecule> ) {0,1}; 

occurs_in: ( @\<AnatomicalEntity> ) {0,1};        
##QUESTION ABOUT ADDING AN OR STATEMENT HERE FOR PROTEIN-CONTAINING COMPLEX, GIVEN THE DEFINITION OF ANATOMICAL ENTITY IN CARO
https://www.ebi.ac.uk/ols/ontologies/caro/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCARO_0000000

has_output: ( @\<ChemicalEntity> OR @\<ProteinContainingComplex> ) *;

has_input:  ( @\<ChemicalEntity> OR @\<ProteinContainingComplex> ) *;

happens_during: ( @\<BiologicalPhase> OR @\<LifeCycleStage> OR @\<PlantStructureDevelopmentStage> ) *;     

causally_upstream_of_or_within: ( @\<BiologicalProcess> ) *;

causally_upstream_of: ( @\<BiologicalProcess> OR @\<MolecularFunction> ) *;

causally_upstream_of_negative_effect: ( @\<BiologicalProcess> OR @\<MolecularFunction> ) *;

causally_upstream_of_positive_effect: ( @\<BiologicalProcess> OR @\<MolecularFunction> ) *;

Add to PREFIX:

PREFIX GoLifeCycleStage: \<http://purl.obolibrary.org/obo/UBERON_0000105>

PREFIX GoPlantStructureDevelopmentStage: \<http://purl.obolibrary.org/obo/PO_0009012>
##CORRECT TERM FROM PO?

**Comment by vanaukenk** [comment]
>##QUESTION ABOUT ADDING AN OR STATEMENT HERE FOR PROTEIN-CONTAINING COMPLEX, GIVEN THE DEFINITION OF ANATOMICAL ENTITY IN CARO
https://www.ebi.ac.uk/ols/ontologies/caro/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCARO_0000000

Discussion with @pgaudet - we will not be annotating MF occurs_in protein-containing complex, so we will just use 'AnatomicalEntity' here.

**Comment by balhoff** [comment]
I realized there are a couple of issues with just using the `AnatomicalEntity` shape for `occurs_in`:

- in the `AnatomicalEntity` shape, we don't say anything about `part_of` relations (but we do allow a *single* `part_of` for `Cell` and `GrossAnatomicalEntity`).
- in the `CellularComponent` shape, we are allowing 3 different `part_of` relations: to a CellularComponent, a Cell, and an Organism.

We need some cleanup here. If we will allow all these `part_of`s for cellular components, then we need to keep using it in an `OR`. Otherwise, we can stick with `AnatomicalEntity` and either say any instance can have a single `part_of`, or change `AnatomicalEntity` to allow those 3 `part_of` possibilities.

**Comment by vanaukenk** [comment]
@balhoff 

Could we do something like this:

\<AnatomicalEntity>@\<GoCamEntity> AND EXTRA a {
 a @\<AnatomicalEntityClass>;
part_of: @\<CellularComponent> {0,1};
part_of: @\<Cell> {0,1};
part_of: @\<GrossAnatomicalEntity> {0,1};
part_of: @\<Organism> {0,1}
}// rdfs:comment  "an anatomical entity"

**Comment by balhoff** [comment]
@vanaukenk that would allow a very star-shaped graph for `part_of`. I thought we were trying to make this a linear chain. Is there any reason to not force it to just be a sequence of single `part_of`? I don't remember the discussion that resulted in the current schema for `CellularComponent`.

**Comment by vanaukenk** [comment]
@balhoff 

Yes, you're right.  I do think we wanted to try to model linear chains, if possible.

In that case, the single 'part of' would be the way to go.

I don't think we'd quite gone through CellularComponent yet as a group, so we should review CC on the next call.

**Comment by balhoff** [comment]
Oh and I forgot the third issue! We need to allow negated cellular components. Should this be generalized to negated anatomical entities?

**Comment by cmungall** [comment]
It seems we are tending towards a simple model that errs on the side of
permissivity

e.g. just using AE, allowing part-of between AEs, and negation of AEs

Note we still get biological inference from OWL, we can prevent biological
impossibilities there, e.g. prokaryote cells part of gross structures

**Comment by balhoff** [comment]
@vanaukenk:

> Discussion with @pgaudet - we will not be annotating MF occurs_in protein-containing complex, so we will just use 'AnatomicalEntity' here.

I think this will be still allowable by the schema, since we are making GO cellular_component a subclass of CARO anatomical_entity, and protein-containing complex is a cellular_component. But wasn't there discussion about moving that anyway?

**Comment by vanaukenk** [comment]
@balhoff 
Wrt the protein-containing complex and 'Anatomical Entity', I was wondering if the definition of 'Anatomical Entity' excluded protein complexes:

"A part of a cellular organism that is either an immaterial entity or a material entity with granularity above the level of a protein complex. Or, a substance produced by a cellular organism with granularity above the level of a protein complex. [ CAROC:Brownsville2014 ]"

**Comment by ukemi** [comment]
This would impinge on the PR that @balhoff created making GO-CC a type of CARO anatomical entity. 
https://github.com/geneontology/go-ontology/pull/17695

**Comment by balhoff** [comment]
Yes, so either we use `AnatomicalEntity OR CellularComponent` everywhere in the schema, or we merge the subclass axiom and we move complexes out of GO cellular_component. Is that possible?

**Comment by ukemi** [comment]
We have considered that before, but it is such a drastic change that I think we would need a lot of lead time. It would create three root nodes in GO.

**Comment by balhoff** [comment]
Here is an alternative proposal: https://github.com/geneontology/go-ontology/issues/17696

**Comment by goodb** [comment]
There are a number of uncontroversial changes in the above.  Could these pushed live while discussion continues on the anatomical entity problem  - perhaps on a separate issue ?

**Comment by pgaudet** [comment]
@goodb 

Yes, these are the decision we had made on the call of 2019-08-07.

@goodb Can you add theese to Shex? 

We have solved the issue with anatomical entity - the new term in now in the ontology https://github.com/geneontology/go-ontology/issues/17696

Thanks, Pascale

**Comment by balhoff** [comment]
@goodb the PR is here: #139

**Comment by goodb** [comment]
@vanaukenk can we close this issue ?  
Noting [this comment](https://github.com/geneontology/go-shapes/pull/167) on your last unmerged branch.
I adjusted slightly and committed to master when it passed the tests.  (Now travis is operational BTW.)

 I set the occurs_in constraint for MF to be occurs_in: ( `@<AnatomicalEntity>` OR `@<ProteinContainingComplex>` ) {0,1};

**Comment by vanaukenk** [comment]
Closing this for now.  
We can re-open or start a new ticket if there are related issues.
