### ISSUE TITLE
Reactome conversion needs its entity ontology for shex validation

### ISSUE THREAD

**Issue by goodb** [geneontology/go-shapes#142]
Everything currently depends on having access to the subclass closure linking instance nodes in the input models to the root classes defined in the shapemap file.  These must be added to the RDF prior to applying the shex patterns.  Currently the scala subclass enricher assumes everything needed is in the rdf.go.org endpoint but this is not currently the case for the reactome models as they depend on an additional ontology.   

This is most likely an edge case.  Jotting it down here to keep in mind and to consider when implementing tools for e.g. pipeline or other environments.

**Comment by ukemi** [comment]
I've thought a bit about this and wonder if we can treat the Reactome entity ontology as an import into Neo. All Reactome entities are either proteins or protein-containing complexes. The limitation I see is that this will create what are essentially equivalent classes for proteins where the Reactome entity refers specifically to the Uniprot protein. However, it does give us the framework for describing proteoforms and complexes based on the Reactome entities. In the future, these can be used as seeds for further import of other resources.

**Comment by goodb** [comment]
@cmungall @kltm what do you think?  Should the [reactome entities](https://github.com/geneontology/pathways2GO/blob/master/exchange/generated/Reactome_physical_entities.owl) be added to neo ?
As it stands, it does make use of uniprot ids where they are available.  These are often then linked to reactome entities (that have other attributes that we don't currently use such as location or PTM information) as equivalents or superclasses.  

Could cause type-ahead confusion???

**Comment by cmungall** [comment]
We should discuss in more detail. I think it could cause a lot of confusion

**Comment by goodb** [comment]
Issue #624 subsumes this one.
