### ISSUE TITLE
Gocamgen model with has_input should pass

### ISSUE THREAD

**Issue by dustine32** [geneontology/go-shapes#148]
In branch:
https://github.com/geneontology/go-shapes/tree/dustine32-test-has_input

I have this [gocamgen-generated](https://github.com/geneontology/gocamgen) test [TTL file](https://github.com/geneontology/go-shapes/blob/dustine32-test-has_input/test_ttl/go_cams/should_pass/WB_WBGene00000903_partial.ttl) with a single assertion individual:
![image](https://user-images.githubusercontent.com/2678599/63188026-32c30a80-c015-11e9-903d-fa59f44bacb4.png)
This model fails both java and python validators despite appearing to follow the ShEx spec:
```
Protein <-enabled_by- MolecularFunction -has_input-> MolecularEntity
```
Here's the python validator output:
```
File: ../test_ttl/go_cams/should_pass/WB_WBGene00000903_partial.ttl Success: False PASS: 4 FAIL: 1
  FAIL: http://model.geneontology.org/0b6b7849-258c-4445-892e-e480610c63fd/09f78549-aae3-4e12-be2f-e27aa601a408 SHAPE: http://purl.obolibrary.org/obo/go/shapes/MolecularFunction REASON:   Testing <http://model.geneontology.org/0b6b7849-258c-4445-892e-e480610c63fd/09f78549-aae3-4e12-be2f-e27aa601a408> against shape N1b900799bad94646b0f0bdc18dea6b82
    Triples:
      <http://model.geneontology.org/0b6b7849-258c-4445-892e-e480610c63fd/09f78549-aae3-4e12-be2f-e27aa601a408> rdf:type obo:GO_0005160 .
      <http://model.geneontology.org/0b6b7849-258c-4445-892e-e480610c63fd/09f78549-aae3-4e12-be2f-e27aa601a408> rdf:type owl:NamedIndividual .
   2 triples exceeds max {1,1}
  Testing <http://model.geneontology.org/0b6b7849-258c-4445-892e-e480610c63fd/09f78549-aae3-4e12-be2f-e27aa601a408> against shape N1b900799bad94646b0f0bdc18dea6b82
    Testing <http://model.geneontology.org/0b6b7849-258c-4445-892e-e480610c63fd/0b95360f-8394-4a17-9687-004a234b64fa> against shape N6baf29f3024240789b58b9a33f3380f4
      Triples:
      <http://model.geneontology.org/0b6b7849-258c-4445-892e-e480610c63fd/0b95360f-8394-4a17-9687-004a234b64fa> rdf:type UniProtKB:P04202 .
      <http://model.geneontology.org/0b6b7849-258c-4445-892e-e480610c63fd/0b95360f-8394-4a17-9687-004a234b64fa> rdf:type owl:NamedIndividual .
   2 triples exceeds max {1,1}
  Testing <http://model.geneontology.org/0b6b7849-258c-4445-892e-e480610c63fd/09f78549-aae3-4e12-be2f-e27aa601a408> against shape N1b900799bad94646b0f0bdc18dea6b82
    Testing <http://model.geneontology.org/0b6b7849-258c-4445-892e-e480610c63fd/0b95360f-8394-4a17-9687-004a234b64fa> against shape N6baf29f3024240789b58b9a33f3380f4
      Testing UniProtKB:P04202 against shape http://purl.obolibrary.org/obo/go/shapes/OwlClass
           No matching triples found for predicate rdf:type
  Testing <http://model.geneontology.org/0b6b7849-258c-4445-892e-e480610c63fd/09f78549-aae3-4e12-be2f-e27aa601a408> against shape N1b900799bad94646b0f0bdc18dea6b82
    Testing <http://model.geneontology.org/0b6b7849-258c-4445-892e-e480610c63fd/0b95360f-8394-4a17-9687-004a234b64fa> against shape N6baf29f3024240789b58b9a33f3380f4
      Triples:
      <http://model.geneontology.org/0b6b7849-258c-4445-892e-e480610c63fd/0b95360f-8394-4a17-9687-004a234b64fa> rdf:type UniProtKB:P04202 .
      <http://model.geneontology.org/0b6b7849-258c-4445-892e-e480610c63fd/0b95360f-8394-4a17-9687-004a234b64fa> rdf:type owl:NamedIndividual .
   2 triples exceeds max {1,1}
  Testing <http://model.geneontology.org/0b6b7849-258c-4445-892e-e480610c63fd/09f78549-aae3-4e12-be2f-e27aa601a408> against shape N1b900799bad94646b0f0bdc18dea6b82
    Testing <http://model.geneontology.org/0b6b7849-258c-4445-892e-e480610c63fd/0b95360f-8394-4a17-9687-004a234b64fa> against shape N6baf29f3024240789b58b9a33f3380f4
         No matching triples found for predicate rdf:type
  Testing <http://model.geneontology.org/0b6b7849-258c-4445-892e-e480610c63fd/09f78549-aae3-4e12-be2f-e27aa601a408> against shape N1b900799bad94646b0f0bdc18dea6b82
    Node kind mismatch have: URIRef expected: bnode
  Testing <http://model.geneontology.org/0b6b7849-258c-4445-892e-e480610c63fd/09f78549-aae3-4e12-be2f-e27aa601a408> against shape N1b900799bad94646b0f0bdc18dea6b82
    Triples:
      <http://model.geneontology.org/0b6b7849-258c-4445-892e-e480610c63fd/09f78549-aae3-4e12-be2f-e27aa601a408> rdf:type obo:GO_0005160 .
      <http://model.geneontology.org/0b6b7849-258c-4445-892e-e480610c63fd/09f78549-aae3-4e12-be2f-e27aa601a408> rdf:type owl:NamedIndividual .
   2 triples exceeds max {1,1}
  Testing <http://model.geneontology.org/0b6b7849-258c-4445-892e-e480610c63fd/09f78549-aae3-4e12-be2f-e27aa601a408> against shape N1b900799bad94646b0f0bdc18dea6b82
       No matching triples found for predicate rdf:type
Final report >> all files successful: False
```
Strange here is that I get a `2 triples exceeds max {1,1}` cardinality violation for predicate `rdf:type` when I'm using this predicate for something that seems so fundamental to our models: "X is an Individual" and "X is of class Y".

Running the validator against the rest of the WB:WBGene00000903 model with this assertion individual removed (so that only simple GP->term assertions remain), I get a PASS result. So I think this would indicate that my general OWL syntax in these models is OK; I'm guessing it's this `has_input` relation that's causing problems.

@balhoff @goodb Are you able to spot anything here that I can change to get it to pass?

Thanks!

**Comment by goodb** [comment]
The problem with this one was that UniProtKB:P04202 doesn't appear to exist in neo in rdf.geneontology.org .  Hence the constraint:
has_input: @<MolecularEntity> *;

is violated by 
    obo:RO_0002233 <http://model.geneontology.org/0b6b7849-258c-4445-892e-e480610c63fd/0b95360f-8394-4a17-9687-004a234b64fa> ;

and 

<http://model.geneontology.org/0b6b7849-258c-4445-892e-e480610c63fd/0b95360f-8394-4a17-9687-004a234b64fa> a UniProtKB:P04202,
        owl:NamedIndividual .

Changing to a different identifier for the protein, which neo knows, allows the file to validate.  

Possibly relevant to https://github.com/geneontology/neo/issues/24

**Comment by goodb** [comment]
@dustine32 is this still a problem for you?  It looks like that uniprot id is still not a part of our universe: e.g. this is a 404 
http://noctua-amigo.berkeleybop.org/amigo/term/UniProtKB:P04202

**Comment by vanaukenk** [comment]
@ukemi @dustine32 

Can we close this ticket?

**Comment by ukemi** [comment]
Good question! The only mouse identifiers that are valid are: MGI identifiers for genes, Protein ontology identifiers for proteins and RNA sequence identifiers for RNAs. If we want curators to be able to enter the uniprot ids, then they need to be translated to either an MGI identifier or a protein ontology identifier. This could be done using the xref column in the GPI file and picking a default as to whether we want them to correspond to a gene or a protein. I think a better approach would be to add an autocomplete restriction to any field that requires a valid entity from NEO as is done in the "Add individual" or 'enabled_by' data entry fields. We should teach curators not to enter the prefix when adding entities. I like it when I enter P04202 into the field that I am given a choice of the gene, the parent protein or an isoform.

**Comment by vanaukenk** [comment]
Okay, I've actually updated the original C. elegans annotation that used a mouse UniProtKB accession in the With/From field to now use the MGI gene identifier.

There is still an issue of what to add in the 'has input' field, but I think the original issue here should now be dealt with.

We still want to do work on constraining the With/From field and eventually using an autocomplete for that, but that's an issue for the Noctua tracker.

Thx.

**Comment by ukemi** [comment]
I think the 'has input' field should be constrained to a valid ontology term. UniProt identifiers for mouse genes are not valid ontology terms, but they are 'synonyms'.

**Comment by vanaukenk** [comment]
@ukemi 

This is a cross-species binding expt where I'll need to decide what the physiologically relevant C. elegans gene should be in the AE.

**Comment by ukemi** [comment]
Got it!  I still think the rule should be that it has to be an ontology term though.
