### ISSUE TITLE
Define relationship with Minerva

### ISSUE THREAD

**Issue by goodb** [geneontology/go-shapes#15]
My original thinking was that the shex validator would end up merged into the main Minerva code and become part of the Minerva deployment.  But, it is convenient to have this repository to isolate issue tracking - and to encourage the development of shex-oriented tooling in other languages.  

Thoughts @balhoff ?

**Comment by cmungall** [comment]
What is the logic that would be implemented here that would not be part of the generic validation mechanism? The explanation part - what else?

**Comment by goodb** [comment]
As it stands, the go_shapes repository does not have integration with Arachne or other reasoners.  This will be needed if we are to provide just-in-time category tagging.  When we move into the Minerva context, we can tap into the existing code there to get this done.  Also, I think a single validation report that includes both the shex results and the owl results (model is inconsistent and why) will be most useful.  

We can continue to develop in separate repos by pre-tagging the input go-cams in one way or another and by deferring any integration with the OWL work.  Otherwise we will start duplicating.  When it is time for integration into Minerva for access via Noctua, we can decide how best to achieve that - e.g. a maven import of the go_shapes project or something else.

**Comment by goodb** [comment]
Right now, all shex and owl validation work is done by Minerva and I think this will stand.  Currently the automated travis checks for this repo work by downloading minerva and running command line operations.
