### ISSUE TITLE
Relations to add to Molecular Function

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-shapes#17]
From discussions on 2019-07-10, there are additional relations to add to MF:

PREFIX GoBiologicalPhase: <http://purl.obolibrary.org/obo/GO_0044848>
happens_during: `@<BiologicalPhase>` *;

regulates: `@<MolecularFunction>` {0,1};

negatively_regulates: `@<MolecularFunction>` {0,1};

positively_regulates: `@<MolecularFunction>` {0,1};

directly_regulates: `@<MolecularFunction>` {0,1};

directly_negatively_regulates: `@<MolecularFunction>` {0,1};

directly_positively_regulates: `@<MolecularFunction>` {0,1};

causally_upstream_of_or_within: `@<BiologicalProcess>` {0,1};

causally_upstream_of_or_within, negative effect: `@<BiologicalProcess>` {0,1};

causally_upstream_of_or_within, positive effect: `@<BiologicalProcess>` {0,1};

causally_upstream_of: `@<BiologicalProcess>` {0,1};

causally_upstream_of, negative effect: `@<BiologicalProcess>` {0,1};

causally_upstream_of, positive effect: `@<BiologicalProcess>` {0,1};

**Comment by ukemi** [comment]
Do we want to keep directly_regulates versus regulates distinctions? If so, we need to specify exactly what they mean.

**Comment by vanaukenk** [comment]
Yes, @pgaudet and I were discussing that.  For now, we included it, but I agree that we need to be clear on when each would be used.

**Comment by cmungall** [comment]
Note that we could make this more stringent. Do we want to say in fact that the MA should have at most one outgoing causal edge of any type? This could be done with a union expression in shex, e.g. `(r1 | r2 | .... | rn)`

**Comment by pgaudet** [comment]
> Do we want to say in fact that the MA should have at most one outgoing causal edge of any type?

We need to look at examples. This is not how I read our diagram from the google doc, but we had not yet gotten to reviewing that part. 

Pascale

**Comment by vanaukenk** [comment]
One relevant example to look at here would be transcription factor activity and how that activity will be related to multiple, downstream targets.  

This remains an outstanding modeling question: do we create one node for the transcription factor activity and link that one node to multiple targets or do we create a separate transcription factor activity node for each individual target?

**Comment by ukemi** [comment]
And if possible, we should try to tease apart the tool behavior from the underlying model. It's pretty clear that if we decide we want to create the separate activities, curators aren't going to want to have to do this manually and will need a way to do it as a 'short cut'.

**Comment by pgaudet** [comment]
> This remains an outstanding modeling question: do we create one node for the transcription factor activity and link that one node to multiple targets or do we create a separate transcription factor activity node for each individual target?

This touches the instance vs class discussion - should we open a ticket for that and discuss pros and cons thoroughly at some point ?

**Comment by vanaukenk** [comment]
There may already be a ticket.  I can look.

**Comment by balhoff** [comment]
These have all been added. They are cardinality `*` rather than `{0,1}`, though so please reopen if that needs to be changed.
