### ISSUE TITLE
Add a .travis.yml

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-shapes#2]
To test any PRs for syntax errors. Ideally it would also test against a test suite of known passes and known failures.

**Comment by cmungall** [comment]
I assume as part of the travis build we would use mvn to compile the java - would be useful to have a pom.xml here

**Comment by ericprud** [comment]
You could go further and have some test cases that you want to pass and to fail. Those are particularly useful anyplace you're being terribly clever. For instance, it's easy for someone to modify an imported schema and one place it gets imported without realizing there are other schemas that import it.

**Comment by goodb** [comment]
@cmungall the travis testing infrastructure is in place.  e.g. see:
https://travis-ci.com/geneontology/GO_Shapes/jobs/214987102

The output is lengthy and not all that informative just yet, but now we can iterate.  
travis yml:  https://github.com/geneontology/GO_Shapes/blob/master/.travis.yml
maven pom:  https://github.com/geneontology/GO_Shapes/blob/master/java/pom.xml
nascent tests:  https://github.com/geneontology/GO_Shapes/blob/master/java/src/test/java/go_shapes/ShexValidatorTest.java
