### ISSUE TITLE
consider using BFO:Process in place of MF in some places.  

### ISSUE THREAD

**Issue by goodb** [geneontology/go-shapes#214]
Coming from the use of root molecular function as a placeholder for when we have no better type as in:
 https://github.com/geneontology/pathways2GO/issues/75#issuecomment-591016144

**Comment by goodb** [comment]
I think this going to be problematic. 

e.g. we have a constraint that the 'directly provides input for' relation can only link an MF to an MF.  
If we type dissociation events as BFO:process, any relations like that attached to them (of which there are many) would be invalid.  And, if we changed the shex to allow relations like (BFO:process 'directly provides input for' BFO:process), then we end up allowing the kinds of MF to BP relations that we were trying to prevent.  

I think we are going to need another more specific class that is a child of BFO:Process and not a parent of MF and BP to handle these cases.  (e.g. 'reaction' as discussed). Then we can model them as we see fit without unintended other consequences.  Or we would need a substantial reworking of our modeling for MF.  

Or we come back to the creation of a specific 'unbinding' class for this case and use that - forcing the problem back to the correct inference of what constitutes such a class in the reactome world.

**Comment by ukemi** [comment]
I think you are right and that's why we originally chose MF as 'not perfect, but works'. The problem with creating the new class is where it would live. We could create it locally, but I always worry about that. It doesn't work to make it an MF because we would like to keep the restriction that those are enabled by gene products. If we were to relax that, then why not just make it MF. We could put it in BFO, but that might be rate-limiting. Any reason why it wouldn't be a parent of MF?

**Comment by goodb** [comment]
It could be a parent of MF, but not both MF and BP.  

This feels like the cellular component ontology problem again.  We could consider the same pattern for the same reasons.  Introduce a new class "Gene Product Function" that is a subclass of MF and is equivalent to any MF that is enabled by a gene product or complex.   This then replaces MF everywhere it is currently used in the same way that 'cellular anatomical entity' is replacing 'cellular component' everywhere.  Then we refer to MF for all of these cases that might not be enabled by something genetically created.  

?

**Comment by ukemi** [comment]
For good ontology exhaustiveness, would we still want the complimentary class or would we just use MF? I'm a bit anxious about essentially changing the definition of our root node:
'A molecular process that can be carried out by the action of a single macromolecular machine, usually via direct physical interactions with other molecular entities. Function in this sense denotes an action, or activity, that a gene product (or a complex) performs. These actions are described from two distinct but related perspectives: (1) biochemical activity, and (2) role as a component in a larger system/process. Source: GOC:pdt'
Although we recently did that anyways. We should ping @cmungall
