### ISSUE TITLE
Declare what constitutes an activity unit

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-shapes#22]
For the Noctua form (and presumably for other reasons), it would be helpful to declare in the specs what constitutes an 'activity unit'.

Could we replace `<MolecularFunction>` below with `<ActivityUnit>` ?

`<MolecularFunction>` `@<TypedMolecularFunction>` AND {
enabled_by: `@<MolecularEntity>` {0,1};
part_of: `@<BiologicalProcess>` {0,1};
occurs_in: `@<CellularComponent>` {0,1};
has_output: `@<MolecularEntity>` *;
has_input: `@<MolecularEntity>` *;
provides_direct_input_for: `@<MolecularFunction>` {0,1};
adding the following seems to break both the js and java shex implementations
for: http://noctua-dev.berkeleybop.org/download/gomodel:R-HSA-156582/owl
directly_positively_regulates: `@<MolecularFunction>` *;
} // rdfs:comment  "A molecular function"

**Comment by goodb** [comment]
@vanaukenk The naming so far has followed the pattern of using the root ontology class that the instances that would fit the shape would have as their 'category'.  e.g. this shape is meant to define all the potential contextual attributes of any instance of a molecular function.  Note that these are not required for it to validate - e.g. it could simply be a node typed with MF and it would pass as long as it didn't have any other properties hanging off of it.  

What do you think of adding a different shape that requires the attributes to be filled in?  e.g. an instance does not match the ActivityUnit shape unless it has an enabler, is part of a bp, etc.

**Comment by vanaukenk** [comment]
> What do you think of adding a different shape that requires the attributes to be filled in? e.g. an instance does not match the ActivityUnit shape unless it has an enabler, is part of a bp, etc.

That's an interesting idea.  I'd like to talk more with @tmushayahama

**Comment by pgaudet** [comment]
@goodb Can you explain what exactly is a shape? 

Are these 'stanzas' shapes ? 

`<MolecularFunction>` `@<TypedMolecularFunction>` AND {
enabled_by: `@<MolecularEntity>` {0,1};
part_of: `@<BiologicalProcess>` {0,1};
occurs_in: `@<CellularComponent>` {0,1};
has_output: `@<MolecularEntity>` *;
has_input: `@<MolecularEntity>` *;
provides_direct_input_for: `@<MolecularFunction>` {0,1};
adding the following seems to break both the js and java shex implementations
for: http://noctua-dev.berkeleybop.org/download/gomodel:R-HSA-156582/owl
directly_positively_regulates: `@<MolecularFunction>` *;
} // rdfs:comment  "A molecular function"

Thanks, Pascale

**Comment by goodb** [comment]
@pgaudet yes a "shape" as I have been using the word here corresponds to blocks like the one for <MolecularFunction>  
They are very much akin to class definitions in an ontology.  If you have time, there is good documentation here:  https://book.validatingrdf.com/bookHtml010.html

**Comment by cmungall** [comment]
What actually is an activity unit?

>

**Comment by pgaudet** [comment]
Thanks @goodb 
Reading https://book.validatingrdf.com/bookHtml010.html, it seems like the 'go-cam-shapes.shex' document is a ShExC document. Section 4.2 in that document indicates that shapes can be names using ':name' (I am not sure I am looking at the right thing, because the format you have in the  'go-cam-shapes.shex' document is different (ie they dont use the '<>' characters). 

But assuming this is the same format (since it's also '.shex'), then we could have 

':Molecular entity'
<MolecularFunction> @<GoCamEntity> AND {
  bl:category [GoMolecularFunction:]  ;
enabled_by: @<MolecularEntity> {0,1};
etc

**Comment by pgaudet** [comment]
@cmungall 
> What actually is an activity unit?

In fact we had defined it in the previous version of the GO-CAM spec google doc, but this have been overwritten. I think it's really important that we define stuff. I started a glossary for go-shapes: https://docs.google.com/document/d/14pw6L0YccENKpvQG1rGFLY73zfGp7dk5ZsK8D7saIJA/edit

(we can have this elsewhere; right now it's at least useful for me!). 

Thanks, Pascale

**Comment by cmungall** [comment]
Maybe start a new issue for this? shexc allows all the standard URI
shortening approaches

**Comment by cmungall** [comment]
Still don't understand: if it is the smallest unit (what is a unit?) of a
GO-Cam 'centered around' a MA, how is that different from an MA?

Sorry to be pedantic good to be precise

I suspect the intent for an AU to be an actual grouping of units, i.e what
was previously termed an annoton, but I could be wrong

**Comment by pgaudet** [comment]
I think @thomaspd uses a Molecular Activity as Molecular Function, at least in papers. I think we should run this by him.

**Comment by cmungall** [comment]
Yes, I think the only concept we need here is MolecularActivity

**Comment by cmungall** [comment]
Shall we close this?

**Comment by pgaudet** [comment]
Let's discuss this on today's call. 

We need to be clear that the Activity Unit is not the same as a Molecular Function. In our Noctua documentation, a MF is often described as a Molecular Activity.

**Comment by pgaudet** [comment]
I just read #48 
If we do that, then I think we need to keep 'Activity Unit'.

**Comment by vanaukenk** [comment]
I think we can close this.
