### ISSUE TITLE
fix location of blazegraph-go-lego for travis (once merged into main pipeline)

### ISSUE THREAD

**Issue by goodb** [geneontology/go-shapes#221]
The shex validation system, as implemented in minerva, requires a blazegraph journal containing go-lego (which contains the gene entities from neo).  This will eventually be a stable pipeline product at a stable location.  When that is done https://github.com/geneontology/pipeline/issues/35#issuecomment-609457989 , we can update the travis file for this project and close this ticket.

**Comment by goodb** [comment]
actually this does not impact this repo.  Remote file location for the journal is a minerva problem.

**Comment by kltm** [comment]
Apologies, my intention for this is a ticket to remind us that we're being very bad and that we need a reminder to change this once we get the main pipeline sorted. I don't want the fact that we have an active hack being used to fudge file locations being lost. (See what happened to the owltools build for an example of a hack job getting turning into a "permanent" solution.)

**Comment by goodb** [comment]
Yes, agreed.  Just moved it to more appropriate repo.  https://github.com/geneontology/minerva/issues/304.

**Comment by kltm** [comment]
Apologies--I somehow didn't make that connection.
