### ISSUE TITLE
delete json-model property

### ISSUE THREAD

**Issue by goodb** [geneontology/go-shapes#231]
Some older models are failing the model metadata validation because they have data hanging off of the property
http://geneontology.org/lego/json-model 

I believe the data there should be deleted from the models as it is not used in the current infrastructure.  @kltm confirm?  

Broader question.  Is it a good time to clean up the models in the repo?  Deleting test models, fixing broken production models etc. ?  If we were to want to advertise the noctua-generated collection, it might be a good idea.

**Comment by kltm** [comment]
@goodb History and conclusion here: https://github.com/geneontology/minerva/issues/85
I believe that the data can be cleansed.

**Comment by goodb** [comment]
Looks like @balhoff already tried a cleanse.  Wonder why they are still in there?  Anyway, easy to get rid of them.

**Comment by vanaukenk** [comment]
@goodb @kltm 

Can we close this ticket?
