### ISSUE TITLE
Question about mirroring 'occurs in' relation for MF in BP

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-shapes#24]
We may need to look at existing annotations and if/how this information has been added by curators, but we need to decide if we are going to mirror the location information, e.g. CC, cell, anatomical structure, organism, currently linked to MFs to BPs as well.

**Comment by ukemi** [comment]
Can't we infer this with the correct property chains?

**Comment by vanaukenk** [comment]
Maybe, but I wonder about cases where a curator might create a root MF with a relation to a BP and want to specify more about where the BP takes place.  
We have this situation currently set up in the BP only version of the Noctua form.

**Comment by vanaukenk** [comment]
We have essentially done this in the ShEx, so closing this ticket.
