### ISSUE TITLE
Be sure that RNAs are valid

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-shapes#26]
Currently we have:
<Gene> @<MolecularEntity> AND {
   bl:category [GoGene:]  ;
}// rdfs:comment "a gene (a piece of DNA with a purpose)"

But some groups annotate to RNAs using RNA central IDs. We need to make sure that these are included. Are they categorized as genes?

RNAcentral	URS0000183BED_9606	URS0000183BED_9606		GO:0005615	PMID:26646931	HDA		C	Homo sapiens microRNA 23b (MIR23B), miRNA		miRNA	NCBITaxon:9606	20180319	BHF-UCL	UBERON:0001969

**Comment by cmungall** [comment]
See also #31 I think the hierarchy should be

 * GeneProduct
    * ncRNA
    * Protein

**Comment by cmungall** [comment]
do we have a test case for this?

**Comment by pgaudet** [comment]
I made a ticket to create those: #50

**Comment by vanaukenk** [comment]
See #173
