### ISSUE TITLE
Do we need to specify that has_input and has_output should be different molecular entities?

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-shapes#27]
For a given Molecular Function, do we want to check that the values of 'has input' and 'has output' are different?

Are there cases where that wouldn't be true, either biologically or because the IDs available for 'has input' and 'has output' aren't specific to, say, modified forms of a protein (in which case I'm not sure we'd want to capture this information at all).

**Comment by pgaudet** [comment]
That sounds like a rule rather than a specification of the model ? (or maybe it's the same?)

**Comment by ukemi** [comment]
But that isn't going to always be the case in our modeling. Take the Reactome imports for example. We have decided to allow the same generic entity to represent a protein and a modified form (for now). That specification is coming later.

**Comment by ukemi** [comment]
At least I think that is still the case. With the new representation, behind the scenes the entities might in fact be different since they are in Reactome.

**Comment by ukemi** [comment]
Looking at the Pink/Parkin Mediated Mitophagy model where the PINK1 is cleaved, it does now look like the intact and cleavage product are specified differently (5205671, 5205678). But as you said above, will there be groups that won't necessarily be able to make isoform/modified form distinctions?

**Comment by pgaudet** [comment]
>  We have decided to allow the same generic entity to represent a protein and a modified form (for now). 

If you cannot specify anything different, I would suggest to leave the output blank ? Or is it used as 'provides direct input' for the next reaction'? But I thought that was the previous MF that did that, not the input. 

? 
Pascale

**Comment by deustp01** [comment]
> For a given Molecular Function, do we want to check that the values of 'has input' and 'has output' are different?

If subcellular locations are not recorded, the inputs and outputs of many transport functions are indistinguishable. But for this case there is the mechanical workaround of simply excluding annotations to those classes of transport functions from the check.

**Comment by deustp01** [comment]
> If you cannot specify anything different, I would suggest to leave the output blank ? 

I'm probably not understanding this, because it looks to me like this suggestion would have all annotations of protein kinase activity functions as having no output, and many of those phosphorylated outputs are required inputs for later steps in signaling cascades.

**Comment by ukemi** [comment]
Or are the active enablers in the downstream steps.

**Comment by huaiyumi** [comment]
Since GO-CAM is not going to model protein modifications, most of the reactions in regulatory pathway will have the same ID. Therefore, I don't think this rule is useful in the spec.
On the other hand, has_input and has_output should be avoided in regulatory pathways.

**Comment by ukemi** [comment]
MGI curators have been adding modified proteins to models using PRO identifiers, as well as annotating modified and processed forms using PRO identifiers for quite some time. See http://noctua.berkeleybop.org/editor/graph/gomodel:5ce58dde00001412

**Comment by cmungall** [comment]
I think we can close this issue?
