### ISSUE TITLE
Create example LinkML schema from JSON

### ISSUE THREAD

**Issue by kltm** [geneontology/go-shapes#277]
From today's software call, @sierra-moxon, using the JSON in the `json-export` branch of this repo, will create a draft schema for the JSON products, as well as introduce the basic workflow for validation using LinkML (okay to have this as a software call topic).

**Comment by kltm** [comment]
We'll also be using this for #276

**Comment by kltm** [comment]
@tmushayahama Are there examples of this committed anywhere so far, or does @sierra-moxon need to run the python to get the JSON? If the latter, could you add that info to a README.md in the right directory?

**Comment by tmushayahama** [comment]
@kltm @sierra-moxon lemme commit it as an example file in the json_export repo

**Comment by vanaukenk** [comment]
Completed via work by @sierra-moxon
