### ISSUE TITLE
Add has_primary_input/output to BP shapes?

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-shapes#283]
I just made a model for ascorbate biosynthesis for mouse and it is failing the ShEx.
http://noctua.geneontology.org/editor/graph/gomodel:6348a65d00002622?
Near as I can tell it is because it is failing the BP shape. Although I thought that the relations cascaded to subclasses, it looks like this isn't happening. Do we need to add the more specific input/output terms, to BP of maybe even to specific BPs like metabolic processes and transport?

**Comment by vanaukenk** [comment]
@ukemi Yes, we do need to add these.  
This is listed as a task in the current Annotation Extensions project.

**Comment by vanaukenk** [comment]
Will add:

PREFIX GoMetabolicProcess: \<http://purl.obolibrary.org/obo/GO_0008152>
PREFIX GoTransport: \<http://purl.obolibrary.org/obo/GO_0006810>
PREFIX has_primary_input: \<http://purl.obolibrary.org/obo/RO_0004009>
PREFIX has_primary_output: \<http://purl.obolibrary.org/obo/RO_0004008>

\<MetabolicProcess> @\<BiologicalProcess> AND EXTRA a {
  a @\<MetabolicProcessClass> {1};
  has_primary_input: @\<ChemicalEntity> *;
  has_primary_output: @\<ChemicalEntity> *;
} // rdfs:comment "a metabolic process GO biological process or child"

\<Transport> @\<BiologicalProcess> AND EXTRA a {
  a @\<TransportClass> {1};
  has_primary_input: ( @\<ChemicalEntity> OR @\<AnatomicalEntity> OR @\<ProteinContainingComplex> ) *;
  has_primary_output: ( @\<ChemicalEntity> OR @\<AnatomicalEntity> OR @\<ProteinContainingComplex> ) *;
} // rdfs:comment "a transport GO biological process or child"

@ukemi
