### ISSUE TITLE
Use fully spelled out camel case names for shapes

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-shapes#3]
E.g.

`s/<BP>/BiologicalProcess/`

Also we should decide on BASE, e.g. `$OBO/go/shapes/`

**Comment by ericprud** [comment]
Re BASE, ShEx uses the usual relative URL resolution so the following would produce a collition on `<Shape1>`:
*repo/Foo.shex*
``` shex
IMPORT <Bar> # assuming some conneg to Bar.shex.

<Shape1> {/*some shape*/}
```
*repo/Bar.shex*
``` shex
<Shape1> {/*some other shape*/}
```
It's popular to make shape expression labels be fragments local to the schema:
*repo/Foo.shex*
``` shex
IMPORT <Bar.shex>

<#Shape1> EXTENDS <Bar#Shape1> {/*some shape*/}
```
*repo/Bar.shex*
``` shex
<#Shape1> {/*some other shape*/}
```

**Comment by goodb** [comment]
@cmungall close if satisfied.

**Comment by vanaukenk** [comment]
@cmungall - okay to close this ticket?

Thx.
