### ISSUE TITLE
Use of Gene in the model

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-shapes#31]
It's not clear that we should use Gene in the model (except in cases of target of transcription etc).

Although we use gene IDs in the models, the IRIs are uncommitted as to what kind of entity they represent, and in neo we just assert them to be information macromolecules. In fact a gene is not actually the object of enabled_by, it's really the product of that gene

See also gene LocatedIn cell component - the gene is always located on the chromosome...

**Comment by pgaudet** [comment]
We need to also thing about the complication of using different ID spaces for genes and proteins - the simplest solution would be to use the same ID space and for specific terms specify whether we mean gene or gene product (or something along those lines)

**Comment by ukemi** [comment]
Doesn't NEO take care of this?

**Comment by pgaudet** [comment]
Does it ?

**Comment by vanaukenk** [comment]
See #173
