### ISSUE TITLE
Make sure the specs work for BP only annotations

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-shapes#40]
In the current version of the Noctua form, as well as for the MOD imports, we have 'BP only' annotations modeled as:

gp <- enabled_by <- root MF -> causally upstream of or within (or child) -> BP -> occurs_in -> Cell -> part_of -> Anatomy 

We need to review this to make sure this is what we still want (I think we'll want to review the occurs_in hierarchy) and that the ShEx allows this.

**Comment by cmungall** [comment]
This is a good opportunity to show the hand-authored tests, I will do

**Comment by cmungall** [comment]
do you intend to have occurs_in hanging off BP or MF here?

**Comment by ukemi** [comment]
Don't you think we should allow occurs_in to hang off of both with appropriate property chains in the ontology for location inference? For example, I think it would be safe to say that if a MF is part of a BP and a BP occurs in AE, then the MF occurs in AE. It would also be a reasonable check that if it is asserted that an MF occurs in AE1, and BP occurs in AE2, then AE1 should be part of or overlap AE2.

**Comment by pgaudet** [comment]
Do we have examples ?

**Comment by vanaukenk** [comment]
I think the ShEx reflects our thinking here, so am closing this ticket for now.
