### ISSUE TITLE
Decide if/how to specify negation

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-shapes#41]
This came up on the workbenches call today.

Do we need to specify in the ShEx how negation will be handled?

**Comment by balhoff** [comment]
Yes! Maybe I'll work on this as my first ShEx contribution.

**Comment by pgaudet** [comment]
Do we want the negation on the MF itself ?

**Comment by ukemi** [comment]
I think so. We want the negation to be tied to the GO term. However, we will have to consider what we mean when we add contextual information to the annotation such as location. This gets into some interesting open versus closed world questions.

**Comment by balhoff** [comment]
Are there other restrictions on the model relating to the use of a negated GO term which I should try to add to the schema?

**Comment by ukemi** [comment]
Looking through the existing annotations in AmiGO2, we also have negation associated with Biological Process (4565) and cellular component (2223) annotations.

**Comment by vanaukenk** [comment]
Then we will likely need all three (BP, MF, and CC) for the imports, and probably to accommodate future 'conventional' annotation in Noctua.

**Comment by balhoff** [comment]
Oh yes, thanks for pointing that out.

**Comment by balhoff** [comment]
I think this is fixed by #56 now.
