### ISSUE TITLE
bl:category should point to a biolink model URI

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-shapes#5]
Rather than OBO

e.g. `s/molecular_function:/bl:MolecularActivity/`

May require syncing with tagger code

**Comment by goodb** [comment]
@cmungall it would be helpful to specify the complete set of bl categories we want to use here and provide the mappings from obo URIs to the appropriate category URI.  

Question - do we constrain things such that any individual should only ever have one category tag ?  See discussion in https://github.com/geneontology/GO_Shapes/issues/14

**Comment by pgaudet** [comment]
> it would be helpful to specify the complete set of bl categories we want to use 

I thought the advantage of the SHEX was to specify everything; don't we?

**Comment by goodb** [comment]
@pgaudet not sure what you mean in your question.  The biolink categories define the root types (e.g. molecular function, biological process, etc.).  They are generally equivalent to the root nodes of the ontologies we use.  Their use here allows for better downstream integration with other projects that use the biolink upper level schema.  We could probably do our work with the obo root terms just as well.  

We use them in the schema to play the role of superclasses in the shape definitions.  So we won't enumerate all children, but instead refer to these classes.  All instances (nodes in the go-cams) will have the appropriate upper level category tags added to them automatically.  

make sense?

**Comment by pgaudet** [comment]
Yes, thanks.

**Comment by cmungall** [comment]
no longer relevant
