### ISSUE TITLE
Can MFs be 'part of' other MFs?

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-shapes#52]
Looking at annotation extensions for MF annotations, curators have made 'part of' relations between MFs.  These annotations have also been made in GO-CAM models.

Do we want to allow this?  

If so, we need to add it to the ShEx specs.

**Comment by balhoff** [comment]
@vanaukenk did this come up in the call yesterday? I can't remember.

**Comment by vanaukenk** [comment]
No, we didn't discuss this on yesterday's call.

@thomaspd @pgaudet 
What do we want to do wrt annotating sub-functions in GO-CAM models?

**Comment by ukemi** [comment]
For compound functions, this will be required won't it?

**Comment by vanaukenk** [comment]
@ukemi - I would think so, yes.

We could have one 'main function' and then have 'has part' relations from that to the sub-functions.

**Comment by ukemi** [comment]
But at the instance-level has_part and part_of are inverse properties.

**Comment by vanaukenk** [comment]
Further discussion with @balhoff and @ukemi 

Adding a 'has part' @\<MolecularEntity> *;

should suffice to capture sub-functions, if we want to do that from a curation pov.

**Comment by vanaukenk** [comment]
A related issue for this is whether or not we want to annotate where sub-functions occur in GO-CAM models, e.g. ligand binding 'occurs in' extracellular region'.

**Comment by ukemi** [comment]
We should explore this. It might solve some spatial issues that have crept up recently.

**Comment by balhoff** [comment]
@vanaukenk:

> Adding a 'has part' @<MolecularEntity> *;

I think you meant MolecularFunction?

**Comment by vanaukenk** [comment]
@balhoff - Yes, I've updated the original comment.  Thx.

**Comment by pgaudet** [comment]
@thomaspd @cmungall : Yes

**Comment by vanaukenk** [comment]
ShEx still needs to be updated here.
